name: coverage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Coverage
      run: |
        pip install coverage
        python -m coverage run -m unittest
        python -m coverage html
    - name: Print wd content
      run: ls .
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        directory: ./htmlcov/
        flags: unittests
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.gz
